sys: disable jit on apple aarch64
BurntSushi/rust-pcre2 pull request #16
Opened 2020-08-26 09:07 UTC by b8591340

clang fails with
```
    Undefined symbols for architecture arm64:
      "___clear_cache", referenced from:
          _sljit_generate_code in libforeign.a(pcre2_jit_compile.o)
    ld: symbol(s) not found for architecture arm64
```

I’ve only tested an `aarch64-apple-ios` build, but see [here](https://bugreports.qt.io/browse/QTBUG-62993?gerritReviewStatus=All) and [here](https://github.com/Homebrew/homebrew-core/pull/57419) for the others.

I also disabled it on the equivalent x86_64 targets to keep an identical binary across simulators and Catalyst (`x86_64-apple-ios-macabi`); the latter might be debatable assuming the symbols are there as they should be, and we might want to enable it there.

2020-08-26 12:42 UTC, BurntSushi requested changes
Seems fine to me! But would like to leave a trail of breadcrumbs in the code so that it's easy to tell when or if we should re-enable it again.

2020-08-26 12:42 UTC, BurntSushi commented on pcre2-sys/build.rs
> +    if !target.starts_with("aarch64-apple") &&
Could you add a comment before this `if` block explaining why we don't enable the JIT in these cases?

I might prefer defining a function, `fn enable_jit(builder: &mut cc::Build)` instead, and documenting that as appropriate.

2020-08-27 13:34 UTC, BurntSushi approved these changes

2020-08-27 13:34 UTC, BurntSushi commented on pcre2-sys/build.rs
> +// propagating to all `aarch64`-based targets and the `x86_64` equivalents.
Lovely, thanks so much! :D

2020-08-27 13:35 UTC, merged

2020-08-27 13:38 UTC, BurntSushi commented
This PR is on crates.io in `pcre2-sys 0.2.5`. (I've also updated ripgrep master to use the new version of `pcre2-sys`.)

Thanks again!

2020-09-09 05:58 UTC, carenas commented
a9876e5728903103f18c8c1fbc37101cfeba1125 might help, but it is likely incomplete as the resulting code is known to cause older versions of IOS to crash (unless the iDevice was rooted), you might be interested on testing zherczeg/sljit#90 if the objective is to have JIT enabled in Apple Silicon eventually

2020-09-09 14:07 UTC, BurntSushi commented
@carenas Thanks. Yes, it would be nice to have the JIT enabled on Apple silicon eventually. But not only do I not have access to Apple's new silicon, but I won't have the bandwidth to do that kind of testing anyway. Thank you for the heads up though!