Use pcre2_jit_match if JIT compiled
BurntSushi/rust-pcre2 pull request #17
Opened 2020-10-28 17:40 UTC by Kogia-sima

# Description

From pcre2 documents:

> It is a "fast path" interface to JIT, and it bypasses some of the sanity checks that pcre2_match() applies.

https://www.pcre.org/current/doc/html/pcre2_jit_match.html

After this patch is applied rust-pcre2 uses `pcre2_jit_match` if JIT-compiled, `pcre2_match` otherwise.

# Performance comparison

This change would gain +10-20% performance for regexredux benchmark in [BenchmarksGame](https://benchmarksgame-team.pages.debian.net/benchmarksgame/index.html).

## old version

```console
        Command being timed: "../target/release/regexredux"
        User time (seconds): 4.10
        System time (seconds): 0.15
        Percent of CPU this job got: 223%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.90
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 150504
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 50724
        Voluntary context switches: 23
        Involuntary context switches: 27
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

## New version

```console
        Command being timed: "../target/release/regexredux"
        User time (seconds): 3.83
        System time (seconds): 0.14
        Percent of CPU this job got: 244%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.62
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 150368
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 50718
        Voluntary context switches: 22
        Involuntary context switches: 14
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

2020-10-28 20:54 UTC, BurntSushi requested changes
I'm pretty sure this is not correct and it's why I didn't use `pcre2_jit_match` in the first place. Namely, its API says that it "bypasses some of the sanity checks that `pcre2_match` applies." Is it possible that there exist some inputs that will result in memory unsafety? If so, this option has to be exposed via an `unsafe` tag in the public API of this crate.

Unfortunately, upon a quick review, I don't see any details about what sanity checks are bypassed and what the safety of the routine actually is. I think we need to nail that down before this is used in this crate.

2020-10-29 16:44 UTC, Kogia-sima commented
The PCRE2 specification says:

> When you call pcre2_match(), as well as testing for invalid options, a number of other sanity checks are performed on the arguments. For example, if the subject pointer is NULL, an immediate error is given. Also, unless PCRE2_NO_UTF_CHECK is set, a UTF subject string is tested for validity. In the interests of speed, these checks do not happen on the JIT fast path, and if invalid data is passed, the result is undefined. 

https://www.pcre.org/current/doc/html/pcre2jit.html#SEC11

I think that we don't have to call `pcre2_match_8` everytime in `<Matches as Iterator>::next()` because the option passed to `pcre2_match_8` is constant. Maybe we can bypass this sanity checks after the first call.

2020-10-29 17:14 UTC, BurntSushi commented
That argument seems a little precarious to me. I see where you're coming from, but it's a bit of a stretch. I think the UTF-8 check is the only thing that is problematic here, right? Because we guarantee that pointers are valid. Although, the docs only list these things as examples and don't see to exhaustively specify what other checks might be omitted.

With that in mind, I wonder if the performance improvements you're seeing with `pcre2_jit_match` over `pcre2_match` are just simply the disabling of the UTF-8 check? If so, you might consider [disabling the UTF check](https://docs.rs/pcre2/0.2.3/pcre2/bytes/struct.RegexBuilder.html#method.disable_utf_check), which is exposed as an unsafe API option. If that recovers the performance difference, then perhaps there is no need to use `pcre2_jit_match`. If so, then there is really no way to avoid unsafe here.

However, #5 notes that PCRE2 has added support for running the JIT safely on input that is not valid UTF-8. So if we updated to the latest PCRE2 and exposed that knob, that would be another path forward here. We'd just need to be careful to only allow it to happen when running the JIT, since the non-JIT engine doesn't yet seem to support safely matching UTF-8 without a check that it is valid.

2020-10-29 17:36 UTC, Kogia-sima commented
Ok, Thaks for your detailed explanation. It seems that PCRE2 doesn't yet provide safe and fast way to match for large input data. I'll close the PR because the root of this problem is in the PCRE2, rather than rust-pcre2.

2020-10-29 17:36 UTC, closed without merging

2020-10-29 18:00 UTC, BurntSushi commented
Aye. And note that the benchmark game does not require utf matching as far as I know. So if you disable that, then the utf check won't run AFAIK.

2020-11-07 12:17 UTC, zherczeg commented
It is true, that JIT in PCRE2 has earlier support for invalid UTF than the interpreter, but now both supports it. Please check the
PCRE2_MATCH_INVALID_UTF option here:
http://pcre.org/current/doc/html/pcre2_compile.html

Note: a new version of PCRE2 is coming soon, which fixes some invalid utf related issues. People started to use this relatively new feature and not surprisingly they found some bugs.

2020-11-07 13:18 UTC, BurntSushi commented
Aye yeah I've been meaning to make that avaioable and use it in ripgrep. It's an awesome feature!